driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/api-umbrella']

provisioner:
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.5
  - name: centos-7.0
  - name: debian-7.6
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - omnibus::default
      - python-docutils
      - vagrant_extras::passwordless_internal_ssh
      - gecode::package
      - api-umbrella::omnibus_build
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/api-umbrella
        install_dir: /opt/api-umbrella
