#<% require "kitchen-sync" %>

<% if(ENV["KITCHEN_DRIVER"] == "aws") %>
driver:
  name: ec2
  region: us-west-2
  availability_zone: us-west-2b
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  aws_ssh_key_id: <%= ENV["AWS_SSH_KEY_ID"] %>
  ssh_key: <%= ENV["AWS_SSH_KEY_PATH"] %>
  associate_public_ip: true
  flavor_id: c3.xlarge
  ebs_volume_size: 20
  ebs_delete_on_termination: true
  ebs_device_name: /dev/sda1
  # price: 0.10
<% else %>
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2560
  synced_folders:
    - ['.', '/home/vagrant/api-umbrella']
<% end %>

provisioner:
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-6.5
    run_list: yum-epel::default
    driver:
      image_id: ami-a9de9c99
      username: root
  - name: centos-7.0
    run_list: yum-epel::default
    driver:
      image_id: ami-c7d092f7
      username: centos
  - name: debian-7.8
    run_list: apt::default
    driver:
      image_id: ami-17510927
      username: admin
  - name: ubuntu-12.04
    run_list: apt::default
    driver:
      image_id: ami-2b471c1b
      username: ubuntu
  - name: ubuntu-14.04
    run_list: apt::default
    driver:
      image_id: ami-1b471c2b
      username: ubuntu


suites:
  - name: build
    run_list:
      - omnibus::default
      - python-docutils
      - vagrant_extras::default
      - vagrant_extras::passwordless_internal_ssh
      - api-umbrella::omnibus_build

      # Additional recipes for running tests after install has finished.
      - java::default
      - elasticsearch::default
      - mongodb::default
      - phantomjs::default
      - packages::default
      - services::default
    attributes:
      authorization:
        sudo:
          include_sudoers_d: true
          sudoers_defaults:
            - "env_reset"
            - "!secure_path"
            - "!requiretty"
      elasticsearch:
        version: 1.4.2
        allocated_memory: 256m
      java:
        jdk_version: 7
      mongodb:
        config:
          smallfiles: true
      omnibus:
        build_user: vagrant
        build_user_group: vagrant
        build_dir: /home/vagrant/api-umbrella
        install_dir: /opt/api-umbrella
        env:
          kitchen_driver: <%= ENV["KITCHEN_DRIVER"] %>
          api_umbrella_version: <%= ENV["API_UMBRELLA_VERSION"] %>
          api_umbrella_iteration: <%= ENV["API_UMBRELLA_ITERATION"] %>
          aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
          aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
          aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>
      packages:
        - unbound
      services:
        elasticsearch:
          - start
  - name: test_install_package
    run_list:
      - api-umbrella::omnibus_test_built_package
    attributes:
      omnibus:
        build_dir: /home/vagrant/api-umbrella
        env:
          kitchen_driver: <%= ENV["KITCHEN_DRIVER"] %>
          api_umbrella_version: <%= ENV["API_UMBRELLA_VERSION"] %>
          api_umbrella_iteration: <%= ENV["API_UMBRELLA_ITERATION"] %>
          aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
          aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
          aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>
    driver:
      customize:
        cpus: 1
        memory: 1536
