#!/bin/bash
#
# Perform necessary api-umbrella setup steps
# after package is installed.
#

function error_exit {
  echo "api-umbrella: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

USER=api-umbrella
GROUP=api-umbrella
DEPLOY_USER=api-umbrella-deploy
DEPLOY_GROUP=api-umbrella-deploy

getent group $GROUP > /dev/null || groupadd -r $GROUP
getent passwd $USER > /dev/null || \
  useradd -r -g $GROUP -s /sbin/nologin \
    -d /opt/api-umbrella -c "API Umbrella user" $USER

getent group $DEPLOY_GROUP > /dev/null || groupadd -r $DEPLOY_GROUP
getent passwd $DEPLOY_USER > /dev/null || \
  useradd -r -g $DEPLOY_GROUP -s /bin/bash \
    -d /home/$DEPLOY_USER -c "API Umbrella deployment user" $DEPLOY_USER

# Fix previously created deploy user that couldn't actually login.
if getent passwd $DEPLOY_USER | grep "/sbin/nologin" > /dev/null; then
  usermod -d /home/$DEPLOY_USER -s /bin/bash $DEPLOY_USER
fi

# Create an empty .ssh/authorized_keys file with proper permissions if it
# doesn't already exist.
if [ ! -f /home/$DEPLOY_USER/.ssh/authorized_keys ]; then
  mkdir -p /home/$DEPLOY_USER/.ssh
  touch /home/$DEPLOY_USER/.ssh/authorized_keys
  chown -R $DEPLOY_USER:$DEPLOY_GROUP /home/$DEPLOY_USER
  chmod 700 /home/$DEPLOY_USER
  chmod 700 /home/$DEPLOY_USER/.ssh
  chmod 600 /home/$DEPLOY_USER/.ssh/authorized_keys
fi

chmod 440 /etc/sudoers.d/api-umbrella

mkdir -p /opt/api-umbrella/etc
mkdir -p /opt/api-umbrella/var/db
mkdir -p /opt/api-umbrella/var/log
mkdir -p /opt/api-umbrella/var/run
mkdir -p /opt/api-umbrella/var/tmp
chmod 1777 /opt/api-umbrella/var/tmp

chown -R $USER:$GROUP /opt/api-umbrella/etc /opt/api-umbrella/var
chown -R $DEPLOY_USER:$DEPLOY_GROUP /opt/api-umbrella/embedded/apps

# The ember-rails gem's handling of temp files isn't ideal when multiple users
# might touch the files. So for now, just make these temp files globally
# writable. See:
# https://github.com/emberjs/ember-rails/issues/315#issuecomment-47703370
# https://github.com/emberjs/ember-rails/pull/357
chmod -R 777 /opt/api-umbrella/embedded/apps/web/current/tmp/ember-rails

ln -sf /opt/api-umbrella/bin/api-umbrella /usr/bin/api-umbrella || error_exit "Cannot link api-umbrella to /usr/bin"
ln -sf /opt/api-umbrella/var/log /var/log/api-umbrella || error_exit "Cannot link api-umbrella logs to /var/log"

# Install service, but don't activate.
if command -v chkconfig > /dev/null 2>&1; then
  chkconfig --add api-umbrella || error_exit "Cannot enable api-umbrella service"
elif command -v update-rc.d > /dev/null 2>&1; then
  update-rc.d api-umbrella defaults 85 15 || error_exit "Cannot enable api-umbrella service"
else
  error_exit "No supported init tool found."
fi

exit 0
