#!/bin/bash
#
# Perform necessary api-umbrella setup steps
# after package is installed.
#

function error_exit {
  echo "api-umbrella: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

USER=api-umbrella
GROUP=api-umbrella
DEPLOY_USER=api-umbrella-deploy
DEPLOY_GROUP=api-umbrella-deploy

getent group $GROUP > /dev/null || groupadd -r $GROUP
getent passwd $USER > /dev/null || \
  useradd -r -g $GROUP -s /sbin/nologin \
    -d /opt/api-umbrella -c "API Umbrella user" $USER

getent group $DEPLOY_GROUP > /dev/null || groupadd -r $DEPLOY_GROUP
getent passwd $DEPLOY_USER > /dev/null || \
  useradd -r -g $DEPLOY_GROUP -s /sbin/nologin \
    -d /opt/api-umbrella/embedded/apps -c "API Umbrella deployment user" $DEPLOY_USER

mkdir -p /opt/api-umbrella/etc
mkdir -p /opt/api-umbrella/var/db
mkdir -p /opt/api-umbrella/var/log
mkdir -p /opt/api-umbrella/var/run
mkdir -p /opt/api-umbrella/var/tmp
chmod 1777 /opt/api-umbrella/var/tmp

chown -R api-umbrella:api-umbrella /opt/api-umbrella/etc /opt/api-umbrella/var
chown -R api-umbrella-deploy:api-umbrella-deploy /opt/api-umbrella/embedded/apps

mkdir -p /etc/api-umbrella
ln -sf /opt/api-umbrella/bin/api-umbrella /usr/bin/api-umbrella || error_exit "Cannot link api-umbrella to /usr/bin"
cp /opt/api-umbrella/etc/init.d/api-umbrella /etc/init.d/api-umbrella || error_exit "Cannot copy api-umbrella to /etc/init.d"

# Install service, but don't activate.
if command -v chkconfig > /dev/null 2>&1; then
  chkconfig --add api-umbrella || error_exit "Cannot enable api-umbrella service"
elif command -v update-rc.d > /dev/null 2>&1; then
  update-rc.d api-umbrella defaults 85 15 || error_exit "Cannot enable api-umbrella service"
else
  error_exit "No supported init tool found."
fi

exit 0
